// ============================================================
// WORKOUT DATA — theo lịch tập của bạn
// ============================================================
const SCHEDULE = {
  // 0=CN, 1=T2, 2=T3, 3=T4, 4=T5, 5=T6, 6=T7
  1: {
    day: 'Thứ 2',
    label: 'T2',
    focus: 'Ngực, Tay Sau & Cardio',
    color: '#ef4444',
    icon: '🏋️',
    type: 'strength',
    exercises: [
      {
        id: 'mon_1',
        name: 'Khởi động: Nhảy dây',
        tool: '',
        note: 'Khởi động toàn thân',
        sets: [{ type: 'timed', duration: 300, label: '5 phút' }],
        timerConfig: null,
      },
      {
        id: 'mon_2',
        name: 'Hít đất (dụng cụ hỗ trợ)',
        tool: 'Dụng cụ hít đất',
        note: 'Xuống sâu, kiểm soát từng lần',
        sets: [
          { type: 'reps', target: null, label: 'Tối đa (đến khi sập)' },
          { type: 'reps', target: null, label: 'Tối đa (đến khi sập)' },
          { type: 'reps', target: null, label: 'Tối đa (đến khi sập)' },
          { type: 'reps', target: null, label: 'Tối đa (đến khi sập)' },
        ],
        timerConfig: null,
      },
      {
        id: 'mon_3',
        name: 'Gậy bẻ lò xo',
        tool: 'Gậy lò xo',
        note: 'Ép chậm, giữ 1s ở điểm gập',
        sets: [
          { type: 'reps', target: '15-20', label: '15-20 lần' },
          { type: 'reps', target: '15-20', label: '15-20 lần' },
          { type: 'reps', target: '15-20', label: '15-20 lần' },
          { type: 'reps', target: '15-20', label: '15-20 lần' },
        ],
        timerConfig: null,
      },
      {
        id: 'mon_4',
        name: 'Xe đạp trong nhà — Sprint',
        tool: 'Xe đạp trong nhà',
        note: 'Đạp nước rút (Sprint)',
        sets: [],
        timerConfig: {
          rounds: 5,
          workSec: 60,
          restSec: 60,
          workLabel: 'Đạp NHANH 🚴',
          restLabel: 'Đạp CHẬM / Nghỉ',
        },
      },
    ],
  },

  2: {
    day: 'Thứ 3',
    label: 'T3',
    focus: 'Lưng, Tay Trước & Bụng',
    color: '#3b82f6',
    icon: '🦾',
    type: 'strength',
    exercises: [
      {
        id: 'tue_1',
        name: 'Xà đơn — Pull-up / Chin-up',
        tool: 'Xà đơn',
        note: 'Kéo hết khả năng, kiểm soát khi hạ',
        sets: [
          { type: 'reps', target: null, label: 'Tối đa' },
          { type: 'reps', target: null, label: 'Tối đa' },
          { type: 'reps', target: null, label: 'Tối đa' },
          { type: 'reps', target: null, label: 'Tối đa' },
          { type: 'reps', target: null, label: 'Tối đa' },
        ],
        timerConfig: null,
      },
      {
        id: 'tue_2',
        name: 'Dumbbell Curls — Gập tay',
        tool: 'Tạ tay 10kg',
        note: 'Gập chậm, siết cơ trên đỉnh',
        sets: [
          { type: 'reps', target: '12-15', label: '12-15 lần/tay' },
          { type: 'reps', target: '12-15', label: '12-15 lần/tay' },
          { type: 'reps', target: '12-15', label: '12-15 lần/tay' },
          { type: 'reps', target: '12-15', label: '12-15 lần/tay' },
        ],
        timerConfig: null,
      },
      {
        id: 'tue_3',
        name: 'Dụng cụ kéo bụng — Trượt kiểm soát',
        tool: 'Dụng cụ kéo bụng',
        note: 'Trượt từ từ, kiểm soát cơ',
        sets: [
          { type: 'reps', target: '15-20', label: '15-20 lần' },
          { type: 'reps', target: '15-20', label: '15-20 lần' },
          { type: 'reps', target: '15-20', label: '15-20 lần' },
          { type: 'reps', target: '15-20', label: '15-20 lần' },
        ],
        timerConfig: null,
      },
      {
        id: 'tue_4',
        name: 'Dụng cụ gập bụng — Crunch',
        tool: 'Dụng cụ gập bụng',
        note: 'Gập siết cơ, đừng dùng đà',
        sets: [
          { type: 'reps', target: '20-25', label: '20-25 lần' },
          { type: 'reps', target: '20-25', label: '20-25 lần' },
          { type: 'reps', target: '20-25', label: '20-25 lần' },
          { type: 'reps', target: '20-25', label: '20-25 lần' },
        ],
        timerConfig: null,
      },
    ],
  },

  3: {
    day: 'Thứ 4',
    label: 'T4',
    focus: 'Chân, Vai & HIIT',
    color: '#f59e0b',
    icon: '🦵',
    type: 'strength',
    exercises: [
      {
        id: 'wed_1',
        name: 'Khởi động: Xe đạp trong nhà',
        tool: 'Xe đạp trong nhà',
        note: 'Đạp vừa phải 10 phút',
        sets: [{ type: 'timed', duration: 600, label: '10 phút' }],
        timerConfig: null,
      },
      {
        id: 'wed_2',
        name: 'Goblet Squat',
        tool: 'Tạ tay 10kg',
        note: 'Ôm 1 tạ trước ngực, squat sâu',
        sets: [
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
        ],
        timerConfig: null,
      },
      {
        id: 'wed_3',
        name: 'Dumbbell Press — Đẩy vai',
        tool: 'Tạ tay 10kg',
        note: 'Đẩy thẳng lên, hạ từ từ',
        sets: [
          { type: 'reps', target: 12, label: '12 lần' },
          { type: 'reps', target: 12, label: '12 lần' },
          { type: 'reps', target: 12, label: '12 lần' },
          { type: 'reps', target: 12, label: '12 lần' },
        ],
        timerConfig: null,
      },
      {
        id: 'wed_4',
        name: 'Battle Rope (Mô phỏng) — HIIT',
        tool: 'Battle Rope / Dây thừng',
        note: 'Đánh dây liên tục, hết sức',
        sets: [],
        timerConfig: {
          rounds: 6,
          workSec: 45,
          restSec: 15,
          workLabel: '💥 ĐÁNH DÂY HẾT SỨC',
          restLabel: '😮‍💨 Nghỉ',
        },
      },
    ],
  },

  4: {
    day: 'Thứ 5',
    label: 'T5',
    focus: 'Phục Hồi Tích Cực',
    color: '#10b981',
    icon: '🧘',
    type: 'recovery',
    exercises: [
      {
        id: 'thu_1',
        name: 'Xe đạp trong nhà — Zone 2',
        tool: 'Xe đạp trong nhà',
        note: 'Giữ nhịp tim vùng đốt mỡ (Zone 2), nói chuyện được',
        sets: [{ type: 'timed', duration: 2700, label: '45 phút liên tục' }],
        timerConfig: null,
      },
      {
        id: 'thu_2',
        name: 'Giãn cơ toàn thân',
        tool: '',
        note: 'Giãn từng nhóm cơ, giữ 30s mỗi tư thế',
        sets: [{ type: 'timed', duration: 900, label: '15 phút' }],
        timerConfig: null,
      },
    ],
  },

  5: {
    day: 'Thứ 6',
    label: 'T6',
    focus: 'Toàn Thân — Full Body Circuit',
    color: '#8b5cf6',
    icon: '⚡',
    type: 'circuit',
    circuitNote: 'Tập xoay vòng 5 bài LIÊN TỤC không nghỉ, xong 1 vòng nghỉ 2 phút. Lặp lại 4 vòng.',
    exercises: [
      {
        id: 'fri_1',
        name: 'Hít đất (dụng cụ hỗ trợ)',
        tool: 'Dụng cụ hít đất',
        note: '',
        sets: [
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
        ],
        timerConfig: null,
      },
      {
        id: 'fri_2',
        name: 'Xà đơn',
        tool: 'Xà đơn',
        note: '',
        sets: [
          { type: 'reps', target: null, label: 'Tối đa' },
          { type: 'reps', target: null, label: 'Tối đa' },
          { type: 'reps', target: null, label: 'Tối đa' },
          { type: 'reps', target: null, label: 'Tối đa' },
        ],
        timerConfig: null,
      },
      {
        id: 'fri_3',
        name: 'Lunge — Bước gập gối',
        tool: 'Tạ tay 10kg',
        note: '',
        sets: [
          { type: 'reps', target: 12, label: '12 lần/chân' },
          { type: 'reps', target: 12, label: '12 lần/chân' },
          { type: 'reps', target: 12, label: '12 lần/chân' },
          { type: 'reps', target: 12, label: '12 lần/chân' },
        ],
        timerConfig: null,
      },
      {
        id: 'fri_4',
        name: 'Dụng cụ kéo bụng',
        tool: 'Dụng cụ kéo bụng',
        note: '',
        sets: [
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
          { type: 'reps', target: 15, label: '15 lần' },
        ],
        timerConfig: null,
      },
      {
        id: 'fri_5',
        name: 'Battle Rope (Mô phỏng)',
        tool: 'Battle Rope / Dây thừng',
        note: '',
        sets: [
          { type: 'timed', duration: 45, label: '45 giây' },
          { type: 'timed', duration: 45, label: '45 giây' },
          { type: 'timed', duration: 45, label: '45 giây' },
          { type: 'timed', duration: 45, label: '45 giây' },
        ],
        timerConfig: null,
      },
    ],
  },

  6: {
    day: 'Thứ 7',
    label: 'T7',
    focus: 'Cardio Dồn Dập & Core',
    color: '#f97316',
    icon: '🔥',
    type: 'cardio',
    exercises: [
      {
        id: 'sat_1',
        name: 'Nhảy dây — Tốc độ cao',
        tool: 'Dây nhảy',
        note: 'Nhảy thật nhanh mỗi vòng',
        sets: [],
        timerConfig: {
          rounds: 10,
          workSec: 60,
          restSec: 30,
          workLabel: '🪢 NHẢY DÂY TỐC ĐỘ CAO',
          restLabel: '😮‍💨 Nghỉ 30s',
        },
      },
      {
        id: 'sat_2',
        name: 'Gập bụng chéo',
        tool: 'Dụng cụ gập bụng',
        note: 'Gập chéo hai bên luân phiên',
        sets: [
          { type: 'reps', target: 30, label: '30 lần' },
          { type: 'reps', target: 30, label: '30 lần' },
          { type: 'reps', target: 30, label: '30 lần' },
          { type: 'reps', target: 30, label: '30 lần' },
        ],
        timerConfig: null,
      },
      {
        id: 'sat_3',
        name: 'Xe đạp trong nhà — Lực cản tối đa',
        tool: 'Xe đạp trong nhà',
        note: 'Tăng lực cản nặng nhất, đạp ráng sức',
        sets: [{ type: 'timed', duration: 1200, label: '20 phút ráng sức' }],
        timerConfig: null,
      },
    ],
  },

  0: {
    day: 'Chủ Nhật',
    label: 'CN',
    focus: 'Nghỉ Ngơi (Rest Day)',
    color: '#6b7280',
    icon: '😴',
    type: 'rest',
    exercises: [],
  },
};

const DAY_ORDER = [1, 2, 3, 4, 5, 6, 0]; // T2 → T3 → ... → CN
